version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db-data:/var/lib/mysql
       # - ./db-data/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
     ## restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "9000:80"
     ## restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - ../html:/var/www/html
       - ./log:/var/log/apache2
       #- ./themes/mytheme:/var/www/html/wp-content/themes/mytheme
volumes:
    db-data:
        driver: local
